version: "3"
services:
  server:
    image: config-server
    ports:
        - "8888:8888"
    environment:
      SPRING_RABBITMQ_ADDRESSES: "messaging:5672"
  client:
    image: config-client
    ports:
      - "8080:8080"
    environment:
      SPRING_RABBITMQ_ADDRESSES: "messaging:5672"
    depends_on:
      - server
  messaging:
    image: rabbitmq:3
